'use client'
import { useEffect, useState } from 'react'
import { Activity, ShieldCheck, Radio, ClipboardList, Play, MapPin, CloudDownload, MessagesSquare } from 'lucide-react'
const API=process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000'
type Point={sector_id:string,district:string,pri:number,severity:string,source:string,evidence?:string,components:Record<string,number>}
type Event={id:number,agent:string,message:string,created_at:string}
type Order={id:number,sector_id:string,title:string,priority:string,status:string,protocol_refs:string}
const color=(n:number)=>n>=75?'critical':n>=55?'high':n>=30?'moderate':'low'
export default function Dashboard(){
 const [points,setPoints]=useState<Point[]>([]),[events,setEvents]=useState<Event[]>([]),[orders,setOrders]=useState<Order[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState('System ready — local data boundary active.'),[selected,setSelected]=useState<Point|null>(null)
 const load=async()=>{try{const [p,e,o]=await Promise.all(['risks/heatmap','activity','work-orders'].map(x=>fetch(`${API}/api/v1/${x}`).then(r=>r.json())));setPoints(p);setEvents(e);setOrders(o)}catch{setNotice('API unavailable. Start Docker Compose or the FastAPI service.')}}
 useEffect(()=>{load();const i=setInterval(load,5000);return()=>clearInterval(i)},[])
 const simulate=async()=>{setBusy(true);try{await fetch(`${API}/api/v1/simulation/tick`,{method:'POST'});setNotice('Clearly labelled demo telemetry ingested.')}finally{await load();setBusy(false)}}
 const refreshWeather=async()=>{setBusy(true);try{const r=await fetch(`${API}/api/v1/data/refresh-weather`,{method:'POST'});const d=await r.json();if(!r.ok)throw new Error(d.detail);setNotice(`Real public weather refreshed: ${d.ingested} reference locations. ${d.limitation}`)}catch(e){setNotice(e instanceof Error?e.message:'Weather refresh failed.')}finally{await load();setBusy(false)}}
 const refreshReports=async()=>{setBusy(true);try{const r=await fetch(`${API}/api/v1/data/refresh-munich-reports`,{method:'POST'});const d=await r.json();if(!r.ok)throw new Error(d.detail);setNotice(`Official Munich reports refreshed: ${d.ingested} sanitation-relevant reports. ${d.limitation}`)}catch(e){setNotice(e instanceof Error?e.message:'Report refresh failed.')}finally{await load();setBusy(false)}}
 const loadScenario=async()=>{setBusy(true);try{const r=await fetch(`${API}/api/v1/data/load-realistic-scenario`,{method:'POST'});const d=await r.json();if(!r.ok)throw new Error(d.detail);setNotice(`Realistic training scenario loaded: ${d.ingested} records. ${d.limitation}`)}catch(e){setNotice(e instanceof Error?e.message:'Scenario loading failed.')}finally{await load();setBusy(false)}}
 const dispatch=async(s:string)=>{setBusy(true);try{const r=await fetch(`${API}/api/v1/agents/trigger-dispatch`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sector_id:s})});const d=await r.json();setNotice(d.action==='monitor'?'Risk is below the dispatch threshold.':`Dispatch drafted for ${s}; waiting for human approval.`)}finally{await load();setBusy(false)}}
 return <main>
  <nav><div className="brand"><ShieldCheck/> <span>URBANGUARD</span><small>AI / MUNICIPAL OPS</small></div><div className="sovereign"><span className="dot"/> EU SOVEREIGN · LOCAL-FIRST</div></nav>
  <section className="hero"><div><p className="eyebrow">MUNICH / BAVARIA REFERENCE LOCATIONS</p><h1>Sanitation intelligence<br/><em>at city scale.</em></h1><p className="sub">Combine real public weather evidence with authorised municipal feeds. All dispatches require human approval.</p></div><div className="actions"><button onClick={refreshWeather} disabled={busy}><CloudDownload size={17}/>{busy?'PROCESSING':'REFRESH REAL WEATHER'}</button><button onClick={refreshReports} disabled={busy}><MessagesSquare size={17}/>{busy?'PROCESSING':'REFRESH CITY REPORTS'}</button><button onClick={loadScenario} disabled={busy}><MapPin size={17}/>{busy?'PROCESSING':'LOAD REALISTIC SCENARIO'}</button><button className="secondary" onClick={simulate} disabled={busy}><Play size={17}/>RUN DEMO DATA</button></div></section>
  <p className="notice"><Radio size={15}/>{notice}</p>
  <div className="grid">
    <section className="panel map"><header><span><MapPin/> CITY RISK MAP</span><b>{points.length} ACTIVE LOCATIONS</b></header><div className="mapspace"><div className="river"/>{points.length?points.map((p,i)=><button key={p.sector_id} title={`${p.district}: PRI ${p.pri}. ${p.evidence||''}`} onClick={()=>{setSelected(p);dispatch(p.sector_id)}} className={`pin ${color(p.pri)}`} style={{left:`${13+i*18}%`,top:`${36+(i%2)*26}%`}}><strong>{p.pri}</strong><span>{p.district.split('-')[0]}</span></button>):<div className="empty">Refresh real weather or run clearly labelled demo data.</div>}</div>{selected&&<div className="evidence"><strong>{selected.district} · PRI {selected.pri}/100</strong><span>{selected.source} · transparent score contributors</span><div>{Object.entries(selected.components).map(([name,value])=><i key={name}>{name.replaceAll('_',' ')} <b>{value}</b></i>)}</div>{selected.evidence&&<small>{selected.evidence}</small>}</div>}<footer><i className="low"/>LOW <i className="moderate"/>MODERATE <i className="high"/>HIGH <i className="critical"/>CRITICAL · click a location to draft a reviewed dispatch</footer></section>
   <section className="panel activity"><header><span><Activity/> AGENT ACTIVITY FEED</span><b>LIVE AUDIT</b></header><div className="feed">{events.length?events.map(e=><article key={e.id}><div className="agent">{e.agent}</div><p>{e.message}</p><time>{new Date(e.created_at).toLocaleTimeString()}</time></article>):<div className="empty">No agent activity yet.</div>}</div></section>
  </div>
  <section className="panel orders"><header><span><ClipboardList/> WORK ORDER & ALERT MANAGER</span><b>HUMAN APPROVAL REQUIRED</b></header>{orders.length?<div className="orderlist">{orders.map(o=><article key={o.id}><div><strong>{o.title}</strong><p>{o.sector_id} · {o.priority}</p></div><code>{o.protocol_refs}</code><span className="pending">{o.status.replace('_',' ')}</span></article>)}</div>:<div className="empty">Dispatch a high-risk location to draft an auditable work order.</div>}</section>
 </main>
}
