'use client'
import { useEffect, useState } from 'react'
import { Activity, ShieldCheck, Radio, ClipboardList, Play, MapPin, CloudDownload, MessagesSquare } from 'lucide-react'
const API=(process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000').replace(/\/$/, '')
type Point={sector_id:string,district:string,pri:number,severity:string,source:string,evidence?:string,components:Record<string,number>}
type Event={id:number,agent:string,message:string,created_at:string}
type Order={id:number,sector_id:string,title:string,priority:string,status:string,protocol_refs:string}
const color=(n:number)=>n>=75?'critical':n>=55?'high':n>=30?'moderate':'low'
const offlinePoints:Point[]=[
 {sector_id:'MUC-NEU-05',district:'Neuhausen-Nymphenburg',pri:85.8,severity:'critical',source:'synthetic_scenario',evidence:'Synthetic training scenario: recurring standing water, blocked gully, and waste accumulation near public access.',components:{temperature:18.9,standing_water:30,organic_waste:13.8,sewer_level:7,ph_deviation:1.3,clog_probability:8.8}},
 {sector_id:'MUC-SCH-02',district:'Schwabing-Freimann',pri:69.4,severity:'high',source:'synthetic_scenario',evidence:'Synthetic training scenario: drain obstruction and prolonged pooled water near a pedestrian route.',components:{temperature:18.5,standing_water:24.2,organic_waste:12.2,sewer_level:4.7,ph_deviation:.5,clog_probability:7.9}},
 {sector_id:'MUC-ALT-01',district:'Altstadt-Lehel',pri:47.3,severity:'moderate',source:'synthetic_scenario',evidence:'Synthetic training scenario: pooled water beside a public waste point after rainfall.',components:{temperature:16.8,standing_water:7.5,organic_waste:8.4,sewer_level:0,ph_deviation:.3,clog_probability:3.8}},
 {sector_id:'MUC-GIE-03',district:'Obergiesing-Fasangarten',pri:36.2,severity:'moderate',source:'synthetic_scenario',evidence:'Synthetic training scenario: repeated organic-waste overflow around a collection point.',components:{temperature:15.9,standing_water:2.5,organic_waste:15.2,sewer_level:0,ph_deviation:0,clog_probability:2.2}},
 {sector_id:'MUC-BOG-04',district:'Bogenhausen',pri:14.5,severity:'low',source:'synthetic_scenario',evidence:'Synthetic training scenario: routine water-edge observation with no elevated operational signal.',components:{temperature:14.5,standing_water:1.7,organic_waste:2.8,sewer_level:0,ph_deviation:.8,clog_probability:1}},
]
export default function Dashboard(){
 const [points,setPoints]=useState<Point[]>([]),[events,setEvents]=useState<Event[]>([]),[orders,setOrders]=useState<Order[]>([]),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[offline,setOffline]=useState(false),[notice,setNotice]=useState('Connecting to UrbanGuard API...'),[selected,setSelected]=useState<Point|null>(null)
 const request=async(path:string,options?:RequestInit)=>{let lastError:unknown;for(let attempt=0;attempt<3;attempt++){try{const response=await fetch(`${API}/api/v1/${path}`,options);if(!response.ok)throw new Error(`${response.status} ${response.statusText}`);return await response.json()}catch(error){lastError=error;await new Promise(resolve=>setTimeout(resolve,500*(attempt+1)))}}throw lastError}
 const load=async()=>{setLoading(true);try{const [p,e,o]=await Promise.all(['risks/heatmap','activity','work-orders'].map(x=>request(x)));setPoints(p);setEvents(e);setOrders(o);setOffline(false);setNotice('Connected to UrbanGuard API.')}catch{setPoints(current=>current.length?current:offlinePoints);setOffline(true);setNotice('Backend unavailable after 3 retries. Showing synthetic offline demo data.')}finally{setLoading(false)}}
 useEffect(()=>{load();const i=setInterval(load,10000);return()=>clearInterval(i)},[])
 const run=async(path:string,label:string,options?:RequestInit)=>{setBusy(true);try{if(offline){setNotice(`Offline demo: ${label}. No live municipal action was sent.`);return}const d=await request(path,options);setNotice(d.limitation?`${label}: ${d.limitation}`:`${label}.`)}catch{setOffline(true);setPoints(current=>current.length?current:offlinePoints);setNotice(`${label} could not reach the backend. Offline demo mode is active.`)}finally{await load();setBusy(false)}}
 const simulate=()=>run('simulation/tick','Clearly labelled demo telemetry ingested',{method:'POST'})
 const refreshWeather=()=>run('data/refresh-weather','Real public weather refreshed',{method:'POST'})
 const refreshReports=()=>run('data/refresh-munich-reports','Official city reports refreshed',{method:'POST'})
 const loadScenario=()=>run('data/load-realistic-scenario','Realistic training scenario loaded',{method:'POST'})
 const dispatch=async(s:string)=>{setBusy(true);try{if(offline){const point=points.find(item=>item.sector_id===s);if(point&&point.pri>=30){setOrders(current=>[{id:Date.now(),sector_id:s,title:`Inspect and mitigate vector breeding risk - ${point.district}`,priority:point.pri>=75?'P1 - same day':'P2 - within 24 hours',status:'pending_approval',protocol_refs:'BAV-WS-01, BAV-OHS-02'},...current]);setNotice(`Offline demo dispatch drafted for ${s}; human approval required.`)}else setNotice('Offline demo: risk remains below the dispatch threshold.');return}const d=await request('agents/trigger-dispatch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sector_id:s})});setNotice(d.action==='monitor'?'Risk is below the dispatch threshold.':`Dispatch drafted for ${s}; waiting for human approval.`)}catch{setOffline(true);setNotice('Dispatch could not reach the backend. Offline demo mode is active.')}finally{await load();setBusy(false)}}
 return <main>
  <nav><div className="brand"><ShieldCheck/> <span>URBANGUARD</span><small>AI / MUNICIPAL OPS</small></div><div className="sovereign"><span className="dot"/> EU SOVEREIGN · LOCAL-FIRST</div></nav>
  <section className="hero"><div><p className="eyebrow">MUNICH / BAVARIA REFERENCE LOCATIONS</p><h1>Sanitation intelligence<br/><em>at city scale.</em></h1><p className="sub">Combine real public weather evidence with authorised municipal feeds. All dispatches require human approval.</p></div><div className="actions"><button onClick={refreshWeather} disabled={busy}><CloudDownload size={17}/>{busy?'PROCESSING':'REFRESH REAL WEATHER'}</button><button onClick={refreshReports} disabled={busy}><MessagesSquare size={17}/>{busy?'PROCESSING':'REFRESH CITY REPORTS'}</button><button onClick={loadScenario} disabled={busy}><MapPin size={17}/>{busy?'PROCESSING':'LOAD REALISTIC SCENARIO'}</button><button className="secondary" onClick={simulate} disabled={busy}><Play size={17}/>RUN DEMO DATA</button></div></section>
  <p className="notice"><Radio size={15}/>{loading?'CONNECTING... ':''}{notice}</p>
  {offline&&<p className="notice offline-notice"><Radio size={15}/>OFFLINE DEMO MODE · synthetic data only · reconnecting automatically</p>}
  <div className="grid">
    <section className="panel map"><header><span><MapPin/> CITY RISK MAP</span><b>{points.length} ACTIVE LOCATIONS</b></header><div className="mapspace"><div className="river"/>{points.length?points.map((p,i)=><button key={p.sector_id} title={`${p.district}: PRI ${p.pri}. ${p.evidence||''}`} onClick={()=>{setSelected(p);dispatch(p.sector_id)}} className={`pin ${color(p.pri)}`} style={{left:`${13+i*18}%`,top:`${36+(i%2)*26}%`}}><strong>{p.pri}</strong><span>{p.district.split('-')[0]}</span></button>):<div className="empty">Refresh real weather or run clearly labelled demo data.</div>}</div>{selected&&<div className="evidence"><strong>{selected.district} · PRI {selected.pri}/100</strong><span>{selected.source} · transparent score contributors</span><div>{Object.entries(selected.components).map(([name,value])=><i key={name}>{name.replaceAll('_',' ')} <b>{value}</b></i>)}</div>{selected.evidence&&<small>{selected.evidence}</small>}</div>}<footer><i className="low"/>LOW <i className="moderate"/>MODERATE <i className="high"/>HIGH <i className="critical"/>CRITICAL · click a location to draft a reviewed dispatch</footer></section>
   <section className="panel activity"><header><span><Activity/> AGENT ACTIVITY FEED</span><b>LIVE AUDIT</b></header><div className="feed">{events.length?events.map(e=><article key={e.id}><div className="agent">{e.agent}</div><p>{e.message}</p><time>{new Date(e.created_at).toLocaleTimeString()}</time></article>):<div className="empty">No agent activity yet.</div>}</div></section>
  </div>
  <section className="panel orders"><header><span><ClipboardList/> WORK ORDER & ALERT MANAGER</span><b>HUMAN APPROVAL REQUIRED</b></header>{orders.length?<div className="orderlist">{orders.map(o=><article key={o.id}><div><strong>{o.title}</strong><p>{o.sector_id} · {o.priority}</p></div><code>{o.protocol_refs}</code><span className="pending">{o.status.replace('_',' ')}</span></article>)}</div>:<div className="empty">Dispatch a high-risk location to draft an auditable work order.</div>}</section>
 </main>
}
